# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: blacktemplar/elo-system-testing
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - php -r "file_exists('.env') || copy('.env.test', '.env');"
          - service mysql start
          - mailcatcher
          - mysql -h localhost -u root -proot -e "CREATE DATABASE \`elo-system-test\`"
          - mv /etc/php/7.0/cli/conf.d/20-xdebug.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini.disabled
          - composer config -g github-oauth.github.com bad34b091be5134ead726265da173ccddaba1c2b
          - composer install --no-interaction --no-progress --prefer-dist
          - php artisan key:generate
          - php artisan doctrine:schema:create
          - mv /etc/php/7.0/cli/conf.d/20-xdebug.ini.disabled /etc/php/7.0/cli/conf.d/20-xdebug.ini
          - vendor/bin/phpunit --coverage-clover=coverage.xml
          - if [ $? -eq 0 ]; then bash <(curl -s https://codecov.io/bash); fi
